default: sema RDV1 RDV2 lecteur redacteur
sema: sema.c
	gcc -Wall -g sema.c -o sema
RDV1: RDV1.c
	gcc -Wall -g RDV1.c -o RDV1
RDV2: RDV2.c
	gcc -Wall -g RDV2.c -o RDV2
lecteur: lecteur.c
	gcc -Wall -g lecteur.c -o lecteur
redacteur: redacteur.c
	gcc -Wall -g redacteur.c -o redacteur
clean:
	rm -f td1 sema RDV1 RDV2 lecteur redacteur